# Simple workflow for deploying static content to GitHub Pages
name: Deploy to pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read # to read repository contents
  packages: read # to read packages from registry
  pages: write # to deploy to Pages
  id-token: write # to verify the deployment originates from an appropriate source

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Enable corepack
        run: corepack enable
      - name: Setup .yarnrc.yml
        run: yarn config set npmScopes.codedpalette.npmAuthToken $GITHUB_TOKEN
      - name: Update remote dependencies
        run: yarn add sketches@npm:@codedpalette/sketches@latest
      - name: Install dependencies
        #FIXME: Remove ignore once pixi changes are merged
        run: YARN_CHECKSUM_BEHAVIOR=ignore yarn install --immutable
      - name: Build
        run: yarn build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
